# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LFNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LFNative

  target 'LFNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-haptic', :path => '../node_modules/react-native-haptic'

  end

  target 'LFNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LFNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LFNative-tvOS

  target 'LFNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
